### ISSUE TITLE
Two questions need to discuss 

### ISSUE THREAD

**Issue by FYHu** [UCLCSSA/User-Specification#4]
Please check the markdown version spec.
The issues are 
1. In section 2.3 Personal timetable what if user is in guest mode? 
My Solution:
The scroll bar displays "Please login via UCL"

2.In section 2.4.4 User may choose the library 
Do we agree with this function, personally I agree with it .

Note: Timezone and city issue #1  fixed

**Comment by henryzt** [comment]
My suggestions would be:
1. provide a one-line text indicate user to log in, and provide a minimum (non-distracting) button to log in, when the button is pressed, redirect to "My UCL" (user profile) page to log in.
2. Yes we can and we can do it later.

I think these are rather detailed problems, which we can discuss or change later in the spec's design or even in development but it's good to point out now.

**Comment by jieyouxu** [comment]
Then I think `Guest` mode vs `User` mode vs `Admin` mode would involve differences in permissions, in terms of which actions each actor is allowed to perform and what UI components each actor is entitled to see. This involves authentication, permissions and roles and such.

As for

> User may choose the library

I'm not sure what you mean by that @FYHu? If you mean prioritizing a "favorite" library, then I think it would be mostly trivial.

**Comment by magetron** [comment]
* 1. Two questions should be split up to 2 issues and closed seperately.
* 2. In the initial versions, sign in shall be required to progress any further in the application. Since our main goal is to develop the Minimum Viable Product.
* 3. Regarding choosing libraries, not sure what you meant by that as well, please clarify @FYHu .

Marking as closed. Will open a issue on "user library"

**Comment by magetron** [comment]
Sorry for disturbing. Clicked by a kid at my place.
See issue #7 for future reference.
